version: '2'
services:
  digdag:
    build: .
    volumes:
      - ./project:/project
    ports:
      - "65432:65432"
    depends_on:
      - db
  db:
    image: postgres:9.6
    ports:
      - "7432:5432"
