#!/bin/bash

NAME=${PWD##*docker-}
IMAGE_NAME=${USER%%-*}/${NAME}
docker rm ${NAME}

set -x
if [ "${1}" = "bash" ]; then
    docker run -v ${PWD}:/work -i -t --entrypoint="/bin/bash" --name=${NAME} ${IMAGE_NAME}
else
    docker run -t -v ${PWD}:/work --name=${NAME} ${IMAGE_NAME} $@
fi
